"use client"

/**
 * References — real posts generated by the Chrlit engine for fictional demo
 * brands, grouped by brand. Data comes from lib/reference-data.ts (written by
 * scripts/export-references.ts). Renders nothing until that data exists.
 *
 * Posts come in MIXED aspect ratios (1:1, 4:5, 3:4, 9:16). To never crop them,
 * each brand is a horizontal slider of uniform-HEIGHT cards (width follows the
 * image's own ratio), and the detail modal shows the full image (object-contain).
 */

import { useState, useRef } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { ChevronLeft, ChevronRight } from "lucide-react"
import { REFERENCE_BRANDS, type ReferencePost, type ReferenceBrand } from "@/lib/reference-data"

type Selected = { brand: string; emoji: string; post: ReferencePost } | null

export function References() {
    const [selected, setSelected] = useState<Selected>(null)

    // Only brands that actually have generated posts
    const brands = REFERENCE_BRANDS.filter((b) => b.posts.length > 0)
    if (brands.length === 0) return null

    return (
        <section id="reference" className="relative z-10 py-28 border-t border-white/5 bg-[#050505]">
            <div className="max-w-7xl mx-auto px-6">
                <div className="text-center mb-16">
                    <p className="text-[9px] font-bold uppercase tracking-[0.3em] text-white/20 mb-4">Reference · co Chrlit vytvořil</p>
                    <h2 className="text-4xl md:text-5xl font-black tracking-tighter text-white uppercase">
                        Skutečné značky.<br /><span className="text-aisummit-cinnabar">Skutečné příspěvky.</span>
                    </h2>
                    <p className="text-white/45 text-sm md:text-base mt-5 max-w-2xl mx-auto">
                        Každý příspěvek vygeneroval Chrlit od nuly — obrázek, text i hashtagy. Klikněte na kterýkoliv.
                    </p>
                </div>

                <div className="space-y-14">
                    {brands.map((brand) => (
                        <BrandSlider
                            key={brand.slug}
                            brand={brand}
                            onSelect={(post) => setSelected({ brand: brand.company, emoji: brand.emoji, post })}
                        />
                    ))}
                </div>

                <p className="text-center mt-16 text-[9px] font-bold uppercase tracking-[0.3em] text-white/20">
                    Ukázkové značky · vygenerováno AI v Chrlit
                </p>
            </div>

            {/* Detail modal — full uncropped image + scrollable caption */}
            <AnimatePresence>
                {selected && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
                        onClick={() => setSelected(null)}
                    >
                        <motion.div
                            initial={{ scale: 0.95, y: 20 }}
                            animate={{ scale: 1, y: 0 }}
                            exit={{ scale: 0.95, y: 20 }}
                            className="bg-[#0a0a0a] border border-white/10 rounded-sm max-w-lg w-full overflow-hidden flex flex-col max-h-[90vh]"
                            onClick={(e) => e.stopPropagation()}
                        >
                            {/* whole image, never cropped */}
                            <div className="shrink-0 bg-black flex items-center justify-center">
                                <img
                                    src={selected.post.imageUrl}
                                    alt={selected.brand}
                                    className="w-auto max-w-full max-h-[60vh] object-contain"
                                />
                            </div>
                            <div className="p-5 overflow-y-auto">
                                <div className="flex items-center gap-2 mb-3">
                                    <span className="text-base">{selected.emoji}</span>
                                    <span className="px-2 py-1 bg-white/5 border border-white/10 rounded-sm text-[9px] font-black uppercase tracking-widest text-white/70">{selected.brand}</span>
                                    <span className="text-white/20 text-[9px] ml-auto">Vygenerováno AI</span>
                                </div>
                                <p className="text-white/60 text-sm leading-relaxed whitespace-pre-line">{selected.post.caption}</p>
                                {selected.post.hashtags && (
                                    <p className="text-aisummit-cinnabar/50 text-[10px] font-bold mt-3">{selected.post.hashtags}</p>
                                )}
                            </div>
                            <div className="px-5 py-3 border-t border-white/5 shrink-0">
                                <button onClick={() => setSelected(null)} className="text-[9px] font-black uppercase tracking-widest text-white/30 hover:text-white transition-colors">
                                    ✕ Zavřít
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </section>
    )
}

// ─── Per-brand horizontal slider ────────────────────────────────────

function BrandSlider({ brand, onSelect }: { brand: ReferenceBrand; onSelect: (post: ReferencePost) => void }) {
    const scroller = useRef<HTMLDivElement>(null)
    const shortIndustry = (industry: string) => industry.split("/").pop()?.trim() || industry

    const scrollByDir = (dir: 1 | -1) => {
        const el = scroller.current
        if (!el) return
        el.scrollBy({ left: dir * el.clientWidth * 0.8, behavior: "smooth" })
    }

    return (
        <div>
            {/* Brand header */}
            <div className="flex items-center gap-3 mb-5">
                <span className="text-2xl">{brand.emoji}</span>
                <div>
                    <h3 className="text-lg font-black uppercase tracking-widest text-white leading-none">{brand.company}</h3>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-white/30">{shortIndustry(brand.industry)}</span>
                </div>
                <span className="ml-auto text-[9px] font-bold uppercase tracking-widest text-white/20">{brand.posts.length} příspěvků</span>
            </div>

            {/* Slider */}
            <div className="relative group/slider">
                <div
                    ref={scroller}
                    className="flex gap-3 overflow-x-auto snap-x snap-mandatory pb-2 scroll-smooth [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden"
                >
                    {brand.posts.map((post, i) => (
                        <motion.button
                            key={i}
                            onClick={() => onSelect(post)}
                            className="snap-start shrink-0 relative rounded-sm overflow-hidden border border-white/10 hover:border-white/30 transition-colors group/card bg-black/40"
                            initial={{ opacity: 0 }}
                            whileInView={{ opacity: 1 }}
                            viewport={{ once: true }}
                            transition={{ duration: 0.4 }}
                        >
                            {/* fixed HEIGHT, auto width → whole image, no crop */}
                            <img
                                src={post.imageUrl}
                                alt={`Příspěvek pro ${brand.company}`}
                                loading="lazy"
                                className="h-64 sm:h-72 md:h-80 w-auto object-cover block"
                            />
                            <div className="absolute inset-0 bg-black/0 group-hover/card:bg-black/40 transition-all flex items-center justify-center">
                                <span className="opacity-0 group-hover/card:opacity-100 px-3 py-1.5 border border-white/30 rounded-sm backdrop-blur-sm text-white/90 text-[9px] font-black uppercase tracking-widest transition-all">
                                    Zobrazit
                                </span>
                            </div>
                        </motion.button>
                    ))}
                </div>

                {/* Slider arrows (reveal on hover) */}
                <button
                    onClick={() => scrollByDir(-1)}
                    aria-label="Předchozí"
                    className="absolute left-1 top-1/2 -translate-y-1/2 z-20 w-9 h-9 rounded-full bg-black/70 border border-white/15 backdrop-blur-sm flex items-center justify-center text-white/70 hover:text-white hover:bg-black opacity-0 group-hover/slider:opacity-100 transition-all"
                >
                    <ChevronLeft className="w-4 h-4" />
                </button>
                <button
                    onClick={() => scrollByDir(1)}
                    aria-label="Další"
                    className="absolute right-1 top-1/2 -translate-y-1/2 z-20 w-9 h-9 rounded-full bg-black/70 border border-white/15 backdrop-blur-sm flex items-center justify-center text-white/70 hover:text-white hover:bg-black opacity-0 group-hover/slider:opacity-100 transition-all"
                >
                    <ChevronRight className="w-4 h-4" />
                </button>
            </div>
        </div>
    )
}
