// AUTO-GENERATED by scripts/export-references.ts — do not edit by hand.
// Real posts generated by the Chrlit engine for fictional demo brands (isReference).
// Re-run the export after (re)generating posts.

export interface ReferencePost {
    imageUrl: string
    caption: string
    hashtags: string
}
export interface ReferenceBrand {
    slug: string
    company: string
    industry: string
    emoji: string
    website: string
    posts: ReferencePost[]
}

export const REFERENCE_BRANDS: ReferenceBrand[] = [
  {
    "slug": "flowtask",
    "company": "Flowtask",
    "industry": "Aplikace / SaaS",
    "emoji": "🚀",
    "website": "https://flowtask.app",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-flowtask/ig-carousel/1782012837953-slide0.webp",
        "caption": "Jak zrušit status meetingy a neztratit přehled\n\nSlunce venku pálí, blíží se červencové svátky a tvůj tým ztrácí přehled, co má kdo dodělat. Místo toho, abys lidi dusil na dalším hodinovém status meetingu, ukaž jim to vizuálně.\n\nKanban nástěnky ve Flowtasku rozjedeš doslova za šedesát vteřin. Stačí importovat staré resty z Asany nebo Trella, vizuálně úkoly rozházet do sloupců a okamžitě víš, kde to drhne. Tým nepotřebuje žádné zdlouhavé školení. Všichni rovnou vidí, co mají dělat.\n\nUšetříš každý den 30 minut zbytečného povídání a získáš zpátky kontrolu nad projekty. Dnes je nejdelší den v roce, tak ho neproseď u složitých zahraničních tabulek, které stejně nikdo nechápe.\n\nImportuj svůj projekt za 60 sekund a vyzkoušej Kanban nástěnky na https://flowtask.app/p/kanban-nastenky\n\n#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #kanbannastenky #projektovymanagement #efektivita #freelancecesko #produktivita #organizace",
        "hashtags": "#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #kanbannastenky #projektovymanagement #efektivita #freelancecesko #produktivita #organizace"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-flowtask/ig-posts/1782012684234.webp",
        "caption": "Práce od moře je sen do prvního zrnka písku v klávesnici.\n\nMýtus: Pracuješ s kokosem v ruce, nohy ve vodě a klienti jen spokojeně platí. Realita: Slunce ti tak pere do displeje, že nevidíš ani kurzor. Písek křupe pod klávesami, notebook vaří a hotelová Wi-Fi padá přesně ve chvíli, kdy klient tlačí na finální schválení před červencovými prázdninami. Venku je nejdelší den v roce a ty místo užívání léta potíš krev nad neodeslaným zadáním. Vykašli se na iluze o dokonalém nomádství. Dej si radši do kupy úkoly v nástroji, který bez složitého zaškolování nasadíš za pět minut. Ať máš na to reálné volno konečně čistou hlavu.\n\nHoď si všechny úkoly do kupy na https://flowtask.app a užij si léto s čistou hlavou. Sdílej tohle s kolegou, co plánoval pracovat z pláže, a napiš nám do komentářů, kde se ti v létě pracovalo úplně nejhůř.\n\n#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #flowtaskfreelancecz #produktivita #digitalninomadi #bezstresu #kanbannastenka #ceskysoftware",
        "hashtags": "#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #flowtaskfreelancecz #produktivita #digitalninomadi #bezstresu #kanbannastenka #ceskysoftware"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/audit-screenshots/ig-reels/1782012157613-cover.webp",
        "caption": "Organizuješ nebo pracuješ?\n\nProkrastitasking. Znáš to? Ten pocit, kdy hodinu přebarvuješ štítky a tvoříš dokonalou strukturu složek, ale reálná práce stojí. Multitasking je mýtus. Snažit se dělat tři věci naráz znamená dělat je špatně a pomalu. Vyber si jeden úkol. Dotáhni ho do konce. Zbytek nechej v jednoduchém systému a běž ven. Dnes je nejdelší den v roce, tak ho neprozraď předstíráním práce. Umíš o víkendu úplně vypnout, nebo už v neděli myslíš na pondělí? Dej vědět do komentářů.\n\nUšetři čas na práci, ne na organizování na https://flowtask.app\n\n#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #freelancer #produktivita #efektivita #freelancecesko #tymovaspoluprace #organizace",
        "hashtags": "#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #freelancer #produktivita #efektivita #freelancecesko #tymovaspoluprace #organizace"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/audit-screenshots/ig-reels/1782012389547-cover.webp",
        "caption": "Zahoď ranní maily\n\nNeotvírej maily hned po probuzení. Jeden cizí dotaz a tvoje plány na dopoledne jsou v háji. Vyřeš ranní operativu cestou v metru. Zapni Flowtask, nahoď Sdílené projekty a rozdej úkoly týmu na dvě kliknutí. Žádné zdlouhavé nastavování procesů a vše kompletně v češtině. Získáš absolutní přehled dřív, než dojedeš do kanclu. Je první letní den, tak nebuď v práci do tmy kvůli složitému mikromanagementu. Vyzkoušej to zdarma na 14 dní bez kreditky a užij si dlouhý večer venku.\n\nRozjeď Sdílené projekty zdarma a bez zadávání karty na https://flowtask.app/p/sdilene-projekty\n\n#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #sdileneprojekty #produktivita #timemanagement #organizacecasu #kanbannastenka #ceskysoftware",
        "hashtags": "#flowtask #flowtaskapp #flowtaskcz #rizeniprojektu #sdileneprojekty #produktivita #timemanagement #organizacecasu #kanbannastenka #ceskysoftware"
      }
    ]
  },
  {
    "slug": "brevia",
    "company": "Brevia",
    "industry": "Aplikace / SaaS",
    "emoji": "🚀",
    "website": "https://brevia.ai",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-brevia/ig-posts/1782014445964.webp",
        "caption": "Bojíš se svěřit interní analýzu umělé inteligenci kvůli úniku dat?\n\nVenku je nejdelší den v roce a ty trčíš nad desítkami otevřených PDF. Zpracovat dvousetstránkovou studii potrvá hodiny. Zrychlit to přes veřejnou AI? Nesmysl. Tvoje obava o bezpečnost je naprosto namístě. Brevia analyzuje a shrne dokumenty za pár sekund. Z chaotických textů vytáhne přesná fakta a logickou strukturu. Tvá data navíc šifrujeme podle nejpřísnějších standardů EU a nikdy je nepoužíváme k trénování jiných modelů. Získej zpět pět hodin času týdně a ušetřený večer běž radši strávit s přáteli na Jakubák.\n\nZpracuj své dokumenty rychle a bezpečně na https://brevia.ai/p/ai-shrnuti-dokumentu\n\n#brevia #breviaai #breviaapp #breviaefektivita #bezpecnostdat #produktivita #datovaanalytika #umelainteligence #aisummary #workefficiency",
        "hashtags": "#brevia #breviaai #breviaapp #breviaefektivita #bezpecnostdat #produktivita #datovaanalytika #umelainteligence #aisummary #workefficiency"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-brevia/ig-carousel/1782014631617-slide0.webp",
        "caption": "Nenič si oči. Přečti reporty za tři sekundy.\n\nTvůj čas je moc drahý na to, abys v neděli večer pálil oči u svítícího monitoru. Seniorní lidé ve tvém týmu tráví hodiny administrativním čtením, které nikam nevede. Změň to. Nový tmavý režim v aplikaci Brevia šetří zrak a pravidlo tří sekund ti naservíruje čistá fakta z jakéhokoliv dlouhého dokumentu. Méně omáčky, rychlejší rozhodování.\n\nOtestuj si Brevii hned zítra ráno na svém nejdelším reportu. Získej fakta bez omáčky na https://brevia.ai\n\n#brevia #breviaai #breviaapp #breviaefektivita #produktivita #umelainteligence #worksmart #saasstartup #workefficiency #technology",
        "hashtags": "#brevia #breviaai #breviaapp #breviaefektivita #produktivita #umelainteligence #worksmart #saasstartup #workefficiency #technology"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-brevia/ig-carousel/1782013678967-slide0.webp",
        "caption": "Přečti padesátistránkové PDF za pět minut\n\nMáš zítra ráno prezentovat data z pěti různých reportů a bojíš se, že ti unikne klíčový detail. Zase jsi uvízl u obrazovky s desítkami otevřených tabů a mhouříš oči do PDFka. Tohle přehlcení textem nedává smysl. Pomocí funkce Chytré poznámky v Brevia můžeš okamžitě zredukovat dlouhé studie do čistých faktů. Přestaneš scrollovat, začneš analyzovat. Zpracuj víkendový backlog za pár minut rovnou s ranní kávou a získej zpět pět hodin týdně.\n\nZjednoduš si rešerši a ušetři hodiny práce s Chytrými poznámkami: https://brevia.ai/p/chytre-poznamky\n\n#brevia #breviaai #breviaapp #breviaefektivita #produktivita #chytrepoznamky #usetricas #technology #workefficiency #futureofwork",
        "hashtags": "#brevia #breviaai #breviaapp #breviaefektivita #produktivita #chytrepoznamky #usetricas #technology #workefficiency #futureofwork"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/audit-screenshots/ig-reels/1782014047525-cover.webp",
        "caption": "Zase nedělní přesčas?\n\nNejdelší den v roce a ty pálíš drahý manažerský čas nad stohy dat. Prokousat se 150 stránkami před pondělní poradou znamená obětovat víkend. To je čistá ztráta. Náš uživatel Tomáš nechal Brevii vytáhnout klíčové body. Výsledek? Za 3 minuty měl hotovo a šel ven. Návratnost investice (ROI) do AI uvidíš na vlastních úsporách okamžitě. Nečti omáčku, dělej rozhodnutí. Získej 30% slevu na firemní Team Plan.\n\nZískej okamžité shrnutí a 30% slevu na Team Plan na https://brevia.ai\n\n#brevia #breviaai #breviaapp #breviaefektivita # #produktivita # #umetelainteligence # #management #smartnotes #technology #productivity",
        "hashtags": "#brevia #breviaai #breviaapp #breviaefektivita # #produktivita # #umetelainteligence # #management #smartnotes #technology #productivity"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/audit-screenshots/ig-reels/1782014270910-cover.webp",
        "caption": "Rychločtení je mýtus.\n\nRychločtení u dlouhého zápisu ze schůzky nefunguje. Ztratíš kontext i detaily, které tě zítra u klienta potopí.\n\nNečti nekonečná vlákna a nestrachuj se o compliance. Přepis a souhrn schůzek od Brevia zanalyzuje stostránkový text a vytáhne to podstatné za tři sekundy. Vše bezpečně a bez úniku citlivých klientských dat do veřejných AI modelů.\n\nDnes je nejdelší den v roce. Zavři notebook a běž ven. AI odře tenhle víkendový přesčas za tebe.\n\nZjednoduš si práci na https://brevia.ai/p/prepis-a-souhrn-schuzek\n\n#brevia #breviaai #breviaapp #breviaefektivita #produktivita #bezpecnostdat #konzultant #efektivita #productivity #artificialintelligence",
        "hashtags": "#brevia #breviaai #breviaapp #breviaefektivita #produktivita #bezpecnostdat #konzultant #efektivita #productivity #artificialintelligence"
      }
    ]
  },
  {
    "slug": "chrlit",
    "company": "Chrlit",
    "industry": "",
    "emoji": "⚡",
    "website": "https://chrlit.cz/",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781883342238.webp",
        "caption": "ChatGPT tvůj salon nezná, proto bez složitých promptů zní jako nudný robot.\n\nZkoušela jsi ChatGPT. Vypadl z něj bezduchý text, co vůbec nezní jako ty. Proč? Protože obecná AI tvůj byznys nezná. Abys z ní dostala použitelný obsah, musela bys trávit hodiny laděním složitých promptů. A na to v plném salonu fakt nemáš čas. Chrlit je AI platforma, která automaticky analyzuje tvůj web a bez složitého psaní promptů okamžitě generuje kompletní instagramové příspěvky včetně grafiky, textů a hashtagů. Nasaje tvou vibe, pochopí tvůj brand a rovnou maká. Nech Claude psát složitý kód a ty běž radši užít páteční slunce na zahrádku.\n\nVykašli se na ladění promptů a nech dřít nás. Zadej svůj web na https://chrlit.cz/ a začni chrlit posty bez stresu.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #marketingprosalony #bezpromtovani #umeleinteligence #socialmediasummer #marketingovetipy #automatizaceobsahu",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #marketingprosalony #bezpromtovani #umeleinteligence #socialmediasummer #marketingovetipy #automatizaceobsahu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781864148199.webp",
        "caption": "Tvoje sítě odteď jedou na autopilota, ale zní na 100 % jako ty. Chrlit je oficiálně venku.\n\nStačí zadat odkaz na web tvého salonu nebo prodejny a systém okamžitě nasaje tvůj tón, barvy i služby. Žádné složité prompty a žádný robotický balast. Jen čistá, osobitá tvář tvého byznysu hotová na pár kliknutí. Venku začíná léto a ty máš po šichtě před sebou celý víkend. Vykašli se na večerní potení v Canvě.\n\nZahoď Canvu, zkus to na 7 dní zdarma na https://chrlit.cz/p/7-dni-trial-zdarma a běž radši k vodě.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnisite #podnikani #usetricas #marketingovetipy #automatizaceobsahu #tvorbaobsahu",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnisite #podnikani #usetricas #marketingovetipy #automatizaceobsahu #tvorbaobsahu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781863962449.webp",
        "caption": "Nahlédni do strojovny, kde z klientského webu vyždímáme obsah na celý měsíc.\n\nZajímá tě, jak přesně to děláme? Žádná magie, jen surová výpočetní síla. Vložíš URL klientského webu a náš systém ho okamžitě rozebere na součástky. Nasaje brand manuál, barvy a pochopí tón komunikace. Kašle na složité prompty. Sám vytáhne produkty a napasuje je do profi grafiky se zabijáckým copy. Právě teď nám v kanclu doslova hoří servery, protože freelanceři hromadně generují letní feedy před odjezdem na chatu. Místo hodin zírání do prázdné šablony a dolování nápadů z nudných textů za tebe odmakáme tu největší špínu. Ty jen zkontroluješ výsledek a pošleš ho klientovi.\n\nPřestaň ztrácet čas prokrastinací a hoď tu nejotravnější klientskou rutinu na naše servery hned teď. Běž na https://chrlit.cz/ a vyzkoušej to na vlastní kůži.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #umelainteligence #marketing #copywriting #aigenerator #umeleinteligence #tvorbaobsahu",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #umelainteligence #marketing #copywriting #aigenerator #umeleinteligence #tvorbaobsahu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781863791130.webp",
        "caption": "Tenhle drsný AI hack ti vygeneruje měsíční feed pro klienta za třicet sekund.\n\nVenku pětadvacet ve stínu, pátek odpoledne a ty pořád hniješ u monitoru nad prázdnou Canvou? Složitá správa klientských účtů tě stojí nervy a spoustu peněz za externí grafiky. Vykašli se na to. Zadej URL adresu klienta a Chrlit z ní okamžitě vysaje brand identitu, tón i produkty. Zapomeň na složité vymýšlení promptů. AI ti rovnou vyplivne kompletní posty s grafikou a texty. Zatímco konkurence dál platí copywritery a potí krev u klávesnice, ty máš měsíční plány pro pět klientů vyřešené dřív, než ti zteplá drink na stole. Čistá efektivita bez korporátních keců.\n\nVyzkoušej to zdarma na https://chrlit.cz/ a odpal na víkend s čistou hlavou.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #freelancemarketing #socialsitě #aihack #tvorbaobsahu #socialmediasummer #umeleinteligence",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #freelancemarketing #socialsitě #aihack #tvorbaobsahu #socialmediasummer #umeleinteligence"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781861712569.webp",
        "caption": "Bojíš se robotické AI? Ukaž jí svůj web a běž radši na koupaliště.\n\nPátek odpoledne. V salonu masakr a ty máš večer vymýšlet letní posty. Rveš si vlasy v Canvě, protože máš hrůzu z toho, že umělá inteligence zní jak terminátor a zničí tvůj brand. Blbost. Chrlit kašle na složité prompty. Prostě mu předhodíš URL svého webu a on si sám vytáhne tvoje barvy, fonty i přesný tón komunikace. Během vteřiny ti vyplivne komplet hotové posty s dokonalou grafikou a texty, které zní, jako bys je psala ty sama. Získáš desítky hodin volného času a čistou hlavu na víkend. Žádná nudná robotičina, jen stoprocentní ty. Ušetři si nervy a běž radši sbalit tašku na koupaliště.\n\nNech letní stres za hlavou. Hoď svůj web na https://chrlit.cz/ a nech ho makat za tebe.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnisite #podnikani #umelainteligence #aimarketing #automatizaceobsahu #umeleinteligence",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnisite #podnikani #umelainteligence #aimarketing #automatizaceobsahu #umeleinteligence"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781848290937.webp",
        "caption": "Tvůj salon zažívá předletní nápor, ale Instagram pomalu umírá.\n\nLéto je tady, zákaznice v salonu se perou o termíny a ty nemáš čas přidat ani storíčko. Pátek klepe na dveře, jenže algoritmus výpadky neodpouští. Jak zachránit dosah a nevyhořet? Žádný složitý prompty. Hoď mi odkaz na svůj web a já ti do pár vteřin vyplivnu hotový posty včetně grafiky a textů. Nasaju tvoji identitu, takže to nesmrdí robotem. Získáš stoprocentně autentický obsah, který tě stojí nula minut času. Sbal se a odjeď na chatu. Sítě jedou za tebe.\n\nHoď záchranu svého víkendu na autopilota. Otestuj si to zdarma na https://chrlit.cz/\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #saascz #aimarketing #marketingovetipy #marketing #podnikani #automatizaceobsahu",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #saascz #aimarketing #marketingovetipy #marketing #podnikani #automatizaceobsahu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781757267480.webp",
        "caption": "Nová verze tarifu Creator ti vygeneruje sedmdesát postů za vteřinu.\n\nSpravuješ sítě pro deset klientů a nový tarif Creator ti chrlí sedmdesát postů za vteřinu? Boží. Ale co když ti uprostřed sezóny dojdou limity? Žádný stres. Nemusíš upgradovat celý plán. Prostě si dokup Dodatečné kredity. Jeden tě vyjde na patnáct kaček, nikdy neexpirují a zachrání ti krk, když klient na poslední chvíli vymyslí letní kampaň. Žádné měsíční závazky, prostě platíš jen za to, co reálně vychrlíš. Srovnej si to: ruční práce v Canvě vs. bleskové vygenerování na jedno kliknutí. Ušetři desítky hodin a nech AI makat za tebe.\n\nDokup si Dodatečné kredity za patnáct kaček na https://chrlit.cz/p/dodatecne-kredity a tvoř bez limitů!\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #stopcanve #rychlyposty #bezlimitu #aigenerator #automatizaceobsahu #marketing",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #stopcanve #rychlyposty #bezlimitu #aigenerator #automatizaceobsahu #marketing"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781757139003.webp",
        "caption": "Sobota strávená v Canvě? To si radši provrtám koleno.\n\nZase plánuješ strávit sobotu u Canvy, abys měla co dát na Instagram svého salonu? Vykašli se na to. Nová aplikace Chrlit má v rukávu tři zbraně, které udělají práci za tebe, zatímco ty budeš chytat bronz. Za prvé: Brandový skener. Naťukáš svůj web a Chrlit okamžitě pochopí tvůj styl i barvy. Žádný robotický generik. Za druhé: Chytrý carouselátor. Vyplivne ti hotovou sérii grafik, které na sebe dokonale navazují. Za třetí: Filtr lidskosti. Texty budou znít přesně jako ty – drze, lidsky a bez korporátního bullshitu.\n\nKlikni na https://chrlit.cz/ a zachraň si víkend dřív, než začne sobota.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnisite #bezbullshitu #automatizaceobsahu #marketing #tvorbaobsahu #socialmediasummer",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnisite #bezbullshitu #automatizaceobsahu #marketing #tvorbaobsahu #socialmediasummer"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781757004296.webp",
        "caption": "Ten moment, kdy tvůj copywriter zjistí, že Chrlit píše mnohem líp.\n\nUž žádné hodiny strávené vymýšlením, co sakra napsat na sítě. Chrlit ti vygeneruje hotové instagramové posty s grafikou, textem i hashtagy na jeden klik. Žádný robotický balast, prostě tvůj vlastní tón značky. Tvůj copywriter sice možná tiše pláče v rohu, ale ty máš ušetřené desítky hodin měsíčně.\n\nPřestaň psát popisky ručně a zkus to hned na https://chrlit.cz/\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnimedia #aimarketing #kopirajting #umeleinteligence #aigenerator #podnikani",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnimedia #aimarketing #kopirajting #umeleinteligence #aigenerator #podnikani"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781756895229.webp",
        "caption": "Chrlit má novou aplikaci a ty dál smolíš klientské posty ručně?\n\nPusť tu klávesnici. Naše nová, o dost chytřejší aplikace právě přistála a ty pořád ještě potíš kreativní popisky pro pět klientů najednou? Chrlit teď funguje na jedno kliknutí. Hodíš tam URL klientského webu a sleduješ, jak ti pod rukama roste kompletní, vizuálně sladěný instagramový feed. Bez psaní promptů. Bez nekonečného nastavování šablon v Canvě. Zatímco tvoje konkurence pálí noci nad klientským schvalováním, ty už můžeš mít sbaleno na víkend u vody. Chrlit zanalyzuje brand a vyplivne hotovou práci za třicet vteřin. Ušetříš desítky hodin, které můžeš fakturovat jinde. Nebo prostě konečně vypnout.\n\nOtestuj novou aplikaci zdarma na https://chrlit.cz/ a začni konečně chrlit.\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #freelancemarketing #socialnimedie #socialnimarketing #socialmediasummer #marketing #podnikani",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #freelancemarketing #socialnimedie #socialnimarketing #socialmediasummer #marketing #podnikani"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781160918412.webp",
        "caption": "Srovnané tužky v penálu ti klientský feed samy nenavrhnou.\n\nUž hodinu leštíš monitor a rovnáš kabely do pravého úhlu, jen abys nemusel vymýšlet posty? Prokrastinační úklid je sice fajn, ale tvoje marže kvůli němu krvácejí. Chrlit zanalyzuje weby tvých klientů a vygeneruje kompletní příspěvky včetně grafiky a textů za tebe. Zatímco ty čistíš kávovar, AI odmaká tu nejtěžší část. Ušetři si drahocenný čas na věci, které tě reálně živí.\n\nPřestaň prokrastinovat a hoď práci na AI na https://chrlit.cz/ (nebo tohle nasdílej kolegovi, který dneska zase radši leští stůl).\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnimedia #ai #produktivita #saascz #marketing #aigenerator",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #socialnimedia #ai #produktivita #saascz #marketing #aigenerator"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-chrlit/ig-posts/1781160810548.webp",
        "caption": "Proč ještě pořád trápíš svůj mozek vymýšlením popisků na Instagram?\n\nKdyž je v salonu nebo na prodejně zrovna totální masakr, klienti blázní a ty máš po dvanáctihodinové šichtě ještě sedět u mobilu a potit kreativní popisky? Tvůj mozek není generátor textů na povel. Když ho nutíš tvořit pod tlakem, dopadne to buď vyhořením, nebo trapným tichem na profilu. Nemusíš se učit složité prompty ani se bát, že AI zní jako chladný robot. Chrlit prostě vezme tvůj web, pochopí tvůj styl a okamžitě vygeneruje kompletní instagramové příspěvky včetně grafiky a textů. Deleguj tenhle stres na AI a běž domů s čistou hlavou.\n\nBěž na chrlit.cz, zaregistruj se zdarma a začni chrlit posty bez námahy ještě dnes!\n\n#chrlit #chrlitcz #chrlitai #autopilotobsahu #marketing #socialnimedia #umeleinteligent #automatizaceobsahu #tvorbaobsahu #marketingovetipy",
        "hashtags": "#chrlit #chrlitcz #chrlitai #autopilotobsahu #marketing #socialnimedia #umeleinteligent #automatizaceobsahu #tvorbaobsahu #marketingovetipy"
      }
    ]
  },
  {
    "slug": "kavarna-zrno",
    "company": "Kavárna Zrno",
    "industry": "Gastronomie / Kavárna",
    "emoji": "☕",
    "website": "https://kavarna-zrno.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426132165.webp",
        "caption": "Žádný sirup ani chemie, přesto v našem espressu ucítíte čerstvé borůvky.\n\nČasto se nás u baru ptáte, jak do kávy ty ovocné tóny dostáváme. Tajemství je jednoduché: nijak. Kávová třešeň je ovoce a kvalitní, světle pražená zrna si svou přirozenou chuť borůvek nebo citrusů prostě nesou v sobě. Žádná aromata, jen čistá příroda. Dneska u nás na mlýnku ladíme etiopskou jednodruhovku. Barista Kuba od rána bojuje s červnovým horkem a vlhkostí vzduchu, abyste v každém šálku dostali dokonale vyváženou chuť bez hořkosti. Stavte se o víkendu zchladit a ochutnat, jak chutná opravdová káva bez kompromisů.\n\nObjevte naši aktuální nabídku jednodruhových káv na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnokava #kamvbrne #kava #dnespijem #coffeetime",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnokava #kamvbrne #kava #dnespijem #coffeetime"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426224013.webp",
        "caption": "Opravdu tvoje tělo po každém doušku výběrové kávy zoufale vysychá?\n\nMýtus o tom, že po kávě uschneš, konečně padl. Moderní věda i naši baristé tě uklidní: tvůj oblíbený šálek se normálně počítá do pitného režimu. Žádný stres, tvoje tělo je v bezpečí! Sklenku vody ti ale v Zrnu k espressu nebo filtru přineseme vždycky. Ne kvůli dehydrataci, ale abychom ti očistili chuťové pohárky. Jen tak si naplno užiješ všechny ovocné a čokoládové tóny naší čerstvě pražené jednodruhové arabiky. Zvlášť v tomto horkém červnovém víkendu, kdy ledové cold brew zachraňuje neděli. Jak to máš ty? Piješ ke kávě vodu automaticky, nebo na to občas zapomínáš?\n\nProzkoumej naše aktuální kávové menu na https://kavarna-zrno.cz a přijď otestovat své chuťové pohárky.\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #kavovemyty #baristazivot #specialtycoffeecech #coffeelover #dnespijem",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #kavovemyty #baristazivot #specialtycoffeecech #coffeelover #dnespijem"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426326341.webp",
        "caption": "Tvoje nedělní ráno v pyžamu si zaslouží mnohem lepší kafe než instantní nouzovku.\n\nChceš zažít pohodu jako u nás u stolku, ale zrovna se ti nechce vylézat z postele? Chápeme. Zkouškové nebo náročný pracovní týden si občas žádají ranní klid bez mluvení s lidmi. Proto pro tebe máme naše čerstvě upražená výběrová zrnka na doma. Žádná věda ani kávový snobismus. Naši baristé ti balíček na baru rádi namelou přesně pro tvou oblíbenou přípravu – ať už máš doma french press, nebo si prostě zaléváš klasiku. Stačí zalít vodou a tvůj pokoj zaplaví vůně, která tě příjemně probudí do nového dne. Zvládneš to hravě i napůl spící.\n\nKup si balíček čerstvých zrn přímo na baru nebo na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kavomilci #coffeelover #specialtycoffeecech #prazskakavarna",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kavomilci #coffeelover #specialtycoffeecech #prazskakavarna"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426449765.webp",
        "caption": "Tohle útulné místo u okna je tajnou zbraní proti zkouškovému stresu.\n\n„Tady se píšou ty nejlepší seminárky a pije to nejlepší cappuccino,“ napsala o nás na Instagramu zákaznice Klára. A my jen tiše přikyvujeme. Když venku v Brně vrcholí zkouškové a v centru není k hnutí, náš stůl u okna je perfektní oáza. Rychlá wifi, božský klid na plánování nového týdne a k tomu ledový filtr, který tě nakopne bez následného útlumu. Potřebuješ pořádnou vzpruhu pro mozek? Vůně našich čerstvých skořicových šneků prokazatelně zlepšuje soustředění. Zapomeň na přeplněné knihovny. Přijď si ulovit svůj tichý koutek, vyladit projekty a užít si poctivé kafe od baristů, kteří tě znají jménem.\n\nNaplánuj si své příští produktivní odpoledne přes link v našem bio na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kamvbrne #specialtycoffeecech #kavarnavpraze #kamnakavu",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kamvbrne #specialtycoffeecech #kavarnavpraze #kamnakavu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426739612.webp",
        "caption": "Tohle flat white zachraňuje životy před těžkým pondělím a my máme důkaz.\n\nTahle slova od naší stálice nás neskutečně hřejí u srdce. V Zrnu totiž věříme, že kafe není jen kofeinový doping, ale rituál, který ti vrátí balanc. Zvlášť v neděli odpoledne, kdy už v hlavě straší blížící se týden nebo zkouškové. Na mlýnku máme zrovna čerstvý jednodruhový mikrolot z Kolumbie s přirozenými tóny peckového ovoce a mléčné čokolády. Žádná přepražená hořkost z řetězců. K tomu si dej našeho legendárního teplého šneka z poctivého másla bez chemie a pondělí tě prostě nerozhází. Napiš nám taky svou recenzi, neskutečně rádi je čteme!\n\nCelé naše kávové menu a aktuální nabídku zrnek najdeš na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #brnocoffee #coffeeplace #skoricovysnek #kavarnavpraze",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #brnocoffee #coffeeplace #skoricovysnek #kavarnavpraze"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426847425.webp",
        "caption": "Taky si každé ráno lžeš, že ti dneska bude stačit jen jedno kafe?\n\nSlíbil jsi sám sobě, že dneska dáš jen jeden šálek a dost? Chápeme. Zkouškové v plném proudu, venku začíná letní žár a ty před sebou máš nekonečný den. My tě neprozradíme. Když to jedno kafe bude náš poctivý double shot Flat white z čerstvě upražené jednodruhové arabiky a k odchodu si nenápadně odneseš ještě jedno ledové do kelímku, zůstane to čistě mezi námi. Na mlýnku máme zrovna božskou Etiopii s tóny borůvek, která tě spolehlivě probere i bez chemických sirupů. Stav se pro svou „jedinou“ dávku kofeinu.\n\nDej nám vědět do komentářů, kolikáté „poslední“ kafe dneska vlastně piješ! A naši aktuální nabídku zrn na doma najdeš na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #etiopie #specialtycoffeecech #kavarnavpraze #skoricovysnek",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #etiopie #specialtycoffeecech #kavarnavpraze #skoricovysnek"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426947484.webp",
        "caption": "Nesnášíš ranní fronty na kafe? Máme pro tebe bleskové řešení.\n\nRanní shon tě nemusí připravit o chuťový zážitek. U nás v Zrnu chápeme, že každá minuta se počítá. Proto ti okamžitě po pípnutí kartou přistane v ruce naše ledové Cold brew. Macerujeme ho poctivých 16 hodin z čerstvých afrických zrn, takže chutná přirozeně sladce i bez cukru. K tomu popadni našeho legendárního skořicového šneka a můžeš běžet. Žádné zdržování, žádné kompromisy v kvalitě. Jen čistá energie s sebou na tvůj ranní sprint do kanclu.\n\nUšetři ráno čas a omrkni naše menu na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #brnocoffee #coldbrew #vyberovakava #specialtycoffeecech #kamnakavu #kava",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #brnocoffee #coldbrew #vyberovakava #specialtycoffeecech #kamnakavu #kava"
      }
    ]
  },
  {
    "slug": "studio-lumen",
    "company": "Studio Lumen",
    "industry": "Krása / Salon",
    "emoji": "✂️",
    "website": "https://studio-lumen.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427611118.webp",
        "caption": "Váš strach ze zničených vlasů je oprávněný, pokud kadeřník vynechal mikroskopickou diagnostiku.\n\nVáš tón pleti a struktura vlasu jsou zcela jedinečné. Proto barvení naslepo často končí zklamáním. V našem salonu začínáme každý rituál hloubkovou trichologickou analýzou pod mikroskopem. Zjistíme skutečný stav keratinových vazeb i to, jak vaše vlasy zvládnou letní UV záření a chlor. Na základě dat namícháme šetrnou barvu s plex-ochranou přesně pro váš typ pleti a tvar obličeje. Žádné tipování, jen čistá věda pro zdraví a maximální lesk. Domů od nás navíc dostanete přesný a jednoduchý plán péče, aby váš nový odstín zůstal sytý po celé týdny.\n\nDopřejte svým vlasům vědecky podloženou péči. Navštivte náš web https://studio-lumen.cz a objednejte se na svou osobní trichologickou diagnostiku ještě dnes.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #trichologie #zdravevlasy #vlasovapece #luxusnikadernictvi #mikroskopickaanalyza #barvenivlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #trichologie #zdravevlasy #vlasovapece #luxusnikadernictvi #mikroskopickaanalyza #barvenivlasu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427723691.webp",
        "caption": "Když si myješ vlasy každý den, abys nebyla mastná, ale pokožka spustí nouzový režim.\n\nČím víc myješ, tím víc mastíš. Klasický začarovaný kruh. První horké červnové dny a vlhkost tě nutí mýt si hlavu denně. Jenže pokožka hlavy v panice produkuje ještě víc mazu, aby se chránila. Výsledkem jsou dehydratované délky bez lesku a mastné kořínky už v poledne. Přestaň své vlasy trápit domácím experimentováním. Správná péče začíná pochopením biologie. V našem salonu sázíme na vědu. Pomocí mikroskopické analýzy odhalíme reálný stav tvé pokožky a navrhneme šetrný rituál, který tvé vlasy vrátí do rovnováhy bez agresivní chemie.\n\nChcete vědět, jak je na tom vaše pokožka? Objednejte se na mikroskopickou analýzu na https://studio-lumen.cz a sledujte náš profil pro další vědecky podložené tipy.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #vlasovaanalyza #trichologie #mikroskopickaanalyza #plexochrana #vlasy",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #vlasovaanalyza #trichologie #mikroskopickaanalyza #plexochrana #vlasy"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427843742.webp",
        "caption": "3 mýty o pánském stylingu, kterým věříte a zbytečně si tím kazíte první dojem.\n\nPlánujete úspěšný pracovní týden? Váš vzhled rozhoduje o prvním dojmu během vteřiny. Zapomeňte na levný gel z drogerie, který vlasy jen slepí. Moderní styling vyžaduje precizní střih na míru a produkty, které respektují biologii vaší pokožky. V našem salonu neslibujeme zázraky na počkání, ale doručíme dokonalost podloženou vědeckou analýzou. Během vaší proměny si navíc odpočinete u šálku výběrové kávy nebo sklenky prémiového prosecca. Spojujeme špičkovou péči s dokonalým rituálem relaxace, který vás restartuje před každou důležitou schůzkou. Tento týden máme v rezervačním systému poslední volná místa pro muže, kteří chtějí vypadat bezchybně.\n\nZajistěte si svůj bezchybný střih na tento týden. Rezervujte si svůj termín přes odkaz v našem bio.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystyling #panskystrih #vlasovaanalýza #mikroskopickaanalyza #promenavlasu #barvenivlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystyling #panskystrih #vlasovaanalýza #mikroskopickaanalyza #promenavlasu #barvenivlasu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427959287.webp",
        "caption": "Špatný střih a nekvalitní styling zničí váš první dojem dřív než stihnete promluvit.\n\nDůležitá schůzka vyžaduje stoprocentní vzhled. Jenže běžný styling po dvou hodinách zplihne a levné produkty dráždí pokožku. Vydrží váš účes celodenní tlak? Představujeme exkluzivní drop: prémiový Matte Texture Clay a precizní střih na míru. Naše péče začíná vědeckou mikroskopickou analýzou vlasové pokožky. Navrhneme střih, který drží tvar sám a chráníme ho před ostrým červnovým sluncem. Uvolnili jsme poslední 3 last-minute termíny na tento víkend před Dnem otců. Získejte precizní střih a luxusní stylingový produkt jako dárek k ošetření.\n\nZarezervujte si svůj termín na tento víkend na https://studio-lumen.cz\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #prvnidojem #vlasovaveda #denotcu #mikroskopickaanalyza #ucesy #setrnezesvetleni",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #prvnidojem #vlasovaveda #denotcu #mikroskopickaanalyza #ucesy #setrnezesvetleni"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781428075437.webp",
        "caption": "Kulatý obličej není genetická vada, jen špatně zvolená geometrie střihu.\n\nZákulisí naší práce není o náhodném stříhání. Když do Studia Lumen usednete, nejdřív studujeme geometrii vaší tváře. Kulatý obličej? Žádný problém. Naši stylisté nepoužívají triky, ale čistou fyziku. Správným úhlem střihu a precizní strukturou dokážeme opticky prodloužit profil a vytvořit ostře řezané rysy. Dnes v salonu ladíme detaily pánského stylingu, který přežije i celodenní maraton schůzek bez ztráty objemu. Žádný ulepený vzhled, jen přirozená fixace a zdravé vlasy podložené vědeckým přístupem. Zítra je navíc Den otců – ideální čas nadělit si precizní péči, kterou si zasloužíte.\n\nDarujte si zasloužený rituál péče. Rezervujte si svůj čas pro precizní střih a individuální přístup na https://studio-lumen.cz.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #geometriestrihu #panskystyling #vlasovapece #balayagepraha #ucesy #zdravevlasypraha",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #geometriestrihu #panskystyling #vlasovapece #balayagepraha #ucesy #zdravevlasypraha"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781428167715.webp",
        "caption": "Průměrný střih vás v byznysu stojí body za první dojem.\n\n„Měl jsem důležitou prezentaci a vlasy si žily vlastním životem. V Lumen mi udělali střih, který drží i bez tuny laku,“ říká náš klient Martin. Pánský střih u nás není jen o zkrácení délek. Používáme vědeckou analýzu růstu vlasů a navrhujeme styling, který respektuje tvar vaší lebky. Výsledek? Účes, který ráno upravíte za 30 vteřin a vydrží perfektní až do pozdního večera. Žádné kompromisy, jen špičková kosmetika a precizní práce našich vizionářů. Tento týden máme v rezervačním kalendáři poslední volná místa pro muže, kteří chtějí vypadat bezchybně.\n\nZajistěte si svůj precizní střih ještě dnes na https://studio-lumen.cz\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystrih #mensgroomingprague #vlasovapece #strihani #balayagepraha #promenavlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystrih #mensgroomingprague #vlasovapece #strihani #balayagepraha #promenavlasu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781428259080.webp",
        "caption": "Necháváte vlasy po umytí volně uschnout, abyste je šetřila? Děláte obrovskou chybu.\n\nMokrý vlas bobtná. Voda uvnitř oslabuje jeho vazby a dlouhé schnutí pokožku hlavy i délky doslova unavuje. Výsledek? Matná barva, roztřepené konečky a ztráta elasticity. Máme pro vás třídenní výzvu. Po dalším mytí použijte termoochranu a vlasy vysušte fénem po směru růstu. Sledujte ten okamžitý rozdíl v lesku. Ve Studiu Lumen propojujeme luxus s vědou. Každý krok – od šetrného barvení s plex-ochranou po precizní střihy – stavíme na výsledcích mikroskopické analýzy vaší vlasové struktury. Už žádné hádání naslepo, jen jistota a zdraví. Napište nám do komentářů: Fénujete, nebo necháváte schnout?\n\nChcete vědět, jak podpořit zdraví a lesk své barvy před létem? Rezervujte si konzultaci na https://studio-lumen.cz\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #peceovlasy #vlasovaporadna #vlasy #barvenivlasu #promenavlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #peceovlasy #vlasovaporadna #vlasy #barvenivlasu #promenavlasu"
      }
    ]
  },
  {
    "slug": "vinarstvi-pod-strani",
    "company": "Vinařství Pod Strání",
    "industry": "Gastronomie / Vinařství",
    "emoji": "🍷",
    "website": "https://vinarstvi-podstrani.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428536359.webp",
        "caption": "Chladit víno v mrazáku pět minut před návštěvou je národní sport.\n\nVíkend končí, kufr auta je plný moravských pokladů a vy se nemůžete dočkat, až si doma nalijete. Jenže láhev má teplotu čerstvě uvařeného čaje. Žádnou paniku. Známe to všichni. Mokrá utěrka, mrazák a modlitba k vinařským bohům. U nás ve sklepě sice na správnou teplotu dbáme, ale doma? Tam platí jediné pravidlo: ať vám chutná. Žádné kroužení skleničkou podle pravítka a hledání tónů posekané trávy za úsvitu. Stačí dobrá společnost, otevřená láhev a klid v duši. Víno má lidi spojovat, ne stresovat složitou etiketou.\n\nA pokud vám zásoby na chlazení dochází, mrkněte na náš e-shop https://vinarstvi-podstrani.cz, kde si můžete doplnit moravské poklady přímo do chladničky. Jaký je pak váš zaručený trik na bleskové vychlazení? Napište nám do komentářů.\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #bezstresu #pohoda #sommelier #degustacevina #jiznimorava #frankovka",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #bezstresu #pohoda #sommelier #degustacevina #jiznimorava #frankovka"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428675763.webp",
        "caption": "Zapomeňte na neosobní degustační sály a masový turismus.\n\nU nás v Pod Strání věříme, že nejlepší víno chutná tam, kde se narodilo. V chladivém přítmí našeho historického sklepa, přímo u dubových sudů. Žádný spěch, žádný snobismus. Provedeme vás naší prací a představíme limitované šarže Ryzlinku vlašského, které v běžném obchodě nenajdete. Právě teď, když na Pálavě kvete réva, má sklep tu nejčistší atmosféru. Unikněte z horkého města na klidný víkend a zažijte poctivou degustaci s naším vinařem. Probereme život, půdu i tradici tří generací.\n\nRezervujte si svůj soukromý termín ve sklepě přes odkaz v našem biu.\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #palava #rodinnevinarstvi #frankovka #sommelier #ryzlinkrynsky #degustacevina",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #palava #rodinnevinarstvi #frankovka #sommelier #ryzlinkrynsky #degustacevina"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428787781.webp",
        "caption": "Jak letos poděkovat lidem, se kterými celý rok táhnete za jeden provaz?\n\nAť už chcete potěšit své věrné kolegy, nebo poslat poctivé poděkování za dobrou spolupráci partnerům, se kterými tvoříte společné dílo, zapomeňte na neosobní dárky z obchoďáků. Naše dárkové sety ukrývají to nejlepší z rodinného vinařství pod Strání – poctivé moravské řemeslo a tradici tří generací. Každou lahev pro vás s úctou zabalíme do elegantního boxu, kam rádi přidáme i váš osobní vzkaz. A o bezpečnou cestu až k jejich dveřím se spolehlivě postaráme, takže víno dorazí v naprostém pořádku do 48 hodin.\n\nVyberte si poctivé dárky, které zahřejí u srdce, na https://vinarstvi-podstrani.cz\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #darujmoravu #poctivevino #rodinnevinorstvi #sommelier #vinnysklep #vino",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #darujmoravu #poctivevino #rodinnevinorstvi #sommelier #vinnysklep #vino"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428934210.webp",
        "caption": "Při přepravě archivních vín neriskuji, ale tito vinaři mě donutili změnit názor.\n\n„Objednal jsem limitovanou sadu na oslavu a bál se, v jakém stavu lahve dorazí. Přišly dokonale zabalené, s osobním vzkazem a v perfektní kondici. Chuť Ryzlinku z roku 2021 předčila všechna očekávání,“ píše náš zákazník Karel. Chápeme, že sběratelské kousky si zaslouží stoprocentní péči. Každou lahev balíme ručně s úctou k naší třígenerační práci ve vinohradu. Žádné poškození, žádné kompromisy. Jen čistá radost z poctivého moravského řemesla přímo u vás doma.\n\nDoplňte svůj domácí archiv poctivými kousky z našeho sklepa – odkaz najdete v bio.\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #archivnivino #poctivevino #jiznimorava #vino #rodinnevinarstvi #frankovka",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #archivnivino #poctivevino #jiznimorava #vino #rodinnevinarstvi #frankovka"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781429062744.webp",
        "caption": "Dokážete poznat víno z padesátileté vinice jen podle jednoho doušku?\n\nV roce 1974 vysadil náš děda na trati Pod Strání první keře Veltlínu. Dnes z nich sbíráme hrozny pro naše nejkomplexnější archivní kousky. Je to jedinečný zážitek jak pro zkušené vinaře, tak pro ty, kteří chtějí teprve ochutnat poctivý kus naší historie. Poznáte ve sklenici hluboké kořenité tóny staré révy, nebo vás zaskočí její zemitá síla? Právě pro Den otců jsme otevřeli rodinný archiv a připravili limitovanou sadu těchto vyzrálých klenotů s certifikátem původu. Lahve pro vás sami s úctou a péčí balíme do masivního dřeva přímo u nás ve sklepě, aby k vám domů doputovaly v naprostém pořádku. Dokážete odhadnout potenciál našeho Veltlínu? Napište nám do komentářů, jak starý archiv máte doma.\n\nUdělejte tátovi radost výjimečným dárkem a vyberte si limitovanou sadu na https://vinarstvi-podstrani.cz\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #rodinnevinoradost #jiznimorava #denotcu #frankovka #vinnysklep #vinarstvi",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #rodinnevinoradost #jiznimorava #denotcu #frankovka #vinnysklep #vinarstvi"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781429162815.webp",
        "caption": "Jak poznáte poctivé víno bez složitých pouček a snobského kroužení sklenkou?\n\nZapomeňte na škrobené řeči o tónu kůže a dešťové vody. Skutečné řemeslo poznáte v ústech. Poctivé víno z rodinného vinařství má čistý charakter, který na nic nespěchá. Teď v červnu, kdy nám na vinicích pod Strání zrovna kvetou hlavy révy, dáváme víno do lahví s jediným cílem: ukázat vám opravdovou chuť jižní Moravy. Když k nám přijedete na degustaci do chladného historického sklepa, nebudeme vás zkoušet z chemie. Ukážeme vám, jak teplota okolí mění vůni vlašáku a proč příliš podchlazená lahev v horku úplně ztratí duši. Víno má spojovat, ne rozdělovat.\n\nChcete zažít poctivou degustaci bez snobismu? Vyberte si svůj letní termín na https://vinarstvi-podstrani.cz\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #jiznimorava #poctivevino #degustacevina #frankovka #milovnicivina #gastronomie",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #jiznimorava #poctivevino #degustacevina #frankovka #milovnicivina #gastronomie"
      }
    ]
  },
  {
    "slug": "forma-fitness",
    "company": "Forma Fitness",
    "industry": "Fitness / Wellness",
    "emoji": "🏋️",
    "website": "https://forma-fitness.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429389394.webp",
        "caption": "Ten moment, kdy tě naložená osa poprvé přitlačí k zemi a kolena se třesou.\n\nPocit, že na tebe v přeplněném fitku všichni zírají, když poprvé bojuješ s prázdnou osou, je hrozný. Pravda je ale taková, že každý nějak začínal. U nás ve Forma Fitness se nikdo nesměje. Naopak. Tady tě podržíme.\n\nNáš rychlý tip pro tvůj příští trénink: Než si naložíš váhu, piluj techniku u zdi nebo s kettlebellem před hrudníkem. Získáš jistotu v hlubokém sedu a ochráníš záda před zraněním. Příští týden v tom nemusíš plavat sám. Přijď si pro bezpečný start a fajn partu.\n\nPřestaň tápat v gymu sám. Klikni na https://forma-fitness.cz a začni trénovat chytře.\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #posilovani #silovytrenink #drepuj #cviceni #motivace #silasvaly",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #posilovani #silovytrenink #drepuj #cviceni #motivace #silasvaly"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429500873.webp",
        "caption": "Pravda o rychlé formě do plavek, kterou ti v klasických fitkách záměrně tají.\n\nCelerová šťáva ti týden před dovolenou břišáky nevykouzlí. Zapomeň na zázračné detoxy a pojď na činky. Ve Formě kašleme na pózy – když se ti u první osy klepou kolena, naši trenéři a komunita tě podrží. Shoď strach a začni s lidmi, co tě nenechají ve štychu.\n\nChceš se posunout dál? Klikni na odkaz v našem biu @forma.fitness\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #bezpoz #fitnesskomunita #realnyuspech #osobnitrener #posilovna #hubnuti",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #bezpoz #fitnesskomunita #realnyuspech #osobnitrener #posilovna #hubnuti"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429592798.webp",
        "caption": "Takhle vypadá gym, když zhasnou světla a všichni jdou konečně domů.\n\nV neděli večer plánuješ, jak od pondělka zničíš své limity. My mezitím neleníme. Když odejde poslední dříč, zhasneme hlavní světla, ale práce nekončí. Nastupuje noční směna. Čistíme osy, rovnáme kotouče na gram přesně a chystáme stroje tak, abys ráno mohl rovnou vlítnout na věc. Žádný chaos, žádné poházené jednoručky po zemi. Jen stoprocentně připravené bojiště pro tvůj další progres. Neděláme to pro efekt, ale protože víme, že detaily dělají výsledky. Tvá ranní dávka železa je připravena. Přijď si pro ni.\n\nZarezervuj si svůj ranní trénink přes odkaz v biu @forma.fitness na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenik #gymlife #bezpretvarky #funkcnitrenink #osobnitrener #motivace",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenik #gymlife #bezpretvarky #funkcnitrenink #osobnitrener #motivace"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429709290.webp",
        "caption": "Jak se naučit správný klik bez toho, aby se ti v gymu někdo smál?\n\nKliky nejsou o pouhém kývání hlavou k zemi. Skutečný klik vyžaduje pevné tělo a hrudník až dolů. Bezpečně a bez strachu, že se zraníš nebo tě bude někdo odsuzovat. Chápeme, že začít v obřím fitku plném pózérů může být děsivé. Proto jsme ve Forma Fitness vytvořili speciální startovací program pro začátečníky. Žádné složité stroje, žádný stres. Jen ty, profi trenér a parta lidí na stejné lodi. Naučíme tě základy, vybudujeme reálnou funkční sílu a zdravé tělo, které ti vydrží fungovat roky, ne jen jednu plavkovou sezónu. Nedělní večer je ideální čas udělat první krok.\n\nZajisti si své místo v našem programu pro začátečníky přes odkaz v biu na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnisila #bezstresu #klik #biomechanika #funkcnitrenink #cviceni",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnisila #bezstresu #klik #biomechanika #funkcnitrenink #cviceni"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429807590.webp",
        "caption": "Přestaň v pondělí čekat frontu na benchpress jako na banány.\n\nPondělí v běžném gymu je peklo. Všichni jedou prsa a ty jen smutně koukáš na obsazené lavičky. U nás ve Forma Fitness na fronty nehrajeme. Zatímco ostatní ztrácejí čas čekáním, naši trenéři už pro tebe chystají kruháč, který ti odpálí celé tělo. Žádné stroje, které tě jen omezují, ale poctivá práce s osou, kettlebelly a vlastní vahou. V zákulisí ladíme tréninky tak, abys ani vteřinu nestál. Naše komunita tě nenechá polevit a trenéři pohlídají každý tvůj pohyb. Zapomeň na pondělní benchpress chaos. Pojď makat chytře pod dohledem profíků. Volná místa na zítřek rychle mizí.\n\nRezervuj si svůj zítřejší funkční trénink přes odkaz v biu @forma.fitness.\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #bezfront #ostravafit #cviceni #posilovna #hubnuti",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #bezfront #ostravafit #cviceni #posilovna #hubnuti"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429925132.webp",
        "caption": "Čekala jsem posměch a pohledy, ale místo toho mě hned podpořili.\n\nTohle nám napsala Nikola, která k nám poprvé přišla s obavou, že se ztrapní. Klasický příběh. Chceš začít cvičit, ale bojíš se, že vlezeš mezi namachrované lidi, co tě budou odsuzovat. U nás ve Forma Fitness to tak nefunguje. Žádné kradmé pohledy ani zrcadlové pózy. Naši certifikovaní trenéři tě naučí správnou techniku od úplného základu, bezpečně a bez stresu. Jsme komunita normálních lidí, kteří se navzájem táhnou nahoru. Nedělní večer je ideální čas přestat odkládat změnu. Sbal si věci a pojď na trénink, kde tě nenecháme se flákat, ale od první minuty tě podržíme.\n\nDomluv si svůj první zkušební trénink přes odkaz v biu @forma.fitness nebo přímo na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #sparingpartner #bezpoz #skutecnasila #zdravyzivotnistyl #biomechanika #silasvaly",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #sparingpartner #bezpoz #skutecnasila #zdravyzivotnistyl #biomechanika #silasvaly"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781430022585.webp",
        "caption": "Stačí dvě procenta dole a tvůj výkon v gymu klesne o pětinu.\n\nNejsi slabý, jen jsi dehydratovaný. Mírný nedostatek vody ti sebere až pětinu síly. Pak máš pocit, že na tréninku nestíháš, a zbytečně pochybuješ o svém těle. Pojďme to změnit. Dáme si třídenní hydratační výzvu: každou hodinu vypij jednu sklenici čisté vody. Žádná věda, žádné složité stroje ani drahé doplňky. Jen jednoduchý návyk, který tě nakopne. U nás ve Forma Fitness tě nikdo soudit nebude, ať už začínáš s prázdnou osou nebo teprve sbíráš odvahu vejít. Jsme komunita, která tě podrží a nenechá tě se flákat.\n\nZačni měnit své návyky v přátelském prostředí. Rezervuj si zkušební lekci na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #ostravafit #zdravypohyb #cviceni #vyzivoveporadenstvi #hubnuti",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #ostravafit #zdravypohyb #cviceni #vyzivoveporadenstvi #hubnuti"
      }
    ]
  }
]
