// AUTO-GENERATED by scripts/export-references.ts — do not edit by hand.
// Real posts generated by the Chrlit engine for fictional demo brands (isReference).
// Re-run the export after (re)generating posts.

export interface ReferencePost {
    imageUrl: string
    caption: string
    hashtags: string
}
export interface ReferenceBrand {
    slug: string
    company: string
    industry: string
    emoji: string
    website: string
    posts: ReferencePost[]
}

export const REFERENCE_BRANDS: ReferenceBrand[] = [
  {
    "slug": "kavarna-zrno",
    "company": "Kavárna Zrno",
    "industry": "Gastronomie / Kavárna",
    "emoji": "☕",
    "website": "https://kavarna-zrno.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426132165.webp",
        "caption": "Žádný sirup ani chemie, přesto v našem espressu ucítíte čerstvé borůvky.\n\nČasto se nás u baru ptáte, jak do kávy ty ovocné tóny dostáváme. Tajemství je jednoduché: nijak. Kávová třešeň je ovoce a kvalitní, světle pražená zrna si svou přirozenou chuť borůvek nebo citrusů prostě nesou v sobě. Žádná aromata, jen čistá příroda. Dneska u nás na mlýnku ladíme etiopskou jednodruhovku. Barista Kuba od rána bojuje s červnovým horkem a vlhkostí vzduchu, abyste v každém šálku dostali dokonale vyváženou chuť bez hořkosti. Stavte se o víkendu zchladit a ochutnat, jak chutná opravdová káva bez kompromisů.\n\nObjevte naši aktuální nabídku jednodruhových káv na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnokava #kamvbrne #kava #dnespijem #coffeetime",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnokava #kamvbrne #kava #dnespijem #coffeetime"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426224013.webp",
        "caption": "Opravdu tvoje tělo po každém doušku výběrové kávy zoufale vysychá?\n\nMýtus o tom, že po kávě uschneš, konečně padl. Moderní věda i naši baristé tě uklidní: tvůj oblíbený šálek se normálně počítá do pitného režimu. Žádný stres, tvoje tělo je v bezpečí! Sklenku vody ti ale v Zrnu k espressu nebo filtru přineseme vždycky. Ne kvůli dehydrataci, ale abychom ti očistili chuťové pohárky. Jen tak si naplno užiješ všechny ovocné a čokoládové tóny naší čerstvě pražené jednodruhové arabiky. Zvlášť v tomto horkém červnovém víkendu, kdy ledové cold brew zachraňuje neděli. Jak to máš ty? Piješ ke kávě vodu automaticky, nebo na to občas zapomínáš?\n\nProzkoumej naše aktuální kávové menu na https://kavarna-zrno.cz a přijď otestovat své chuťové pohárky.\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #kavovemyty #baristazivot #specialtycoffeecech #coffeelover #dnespijem",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #kavovemyty #baristazivot #specialtycoffeecech #coffeelover #dnespijem"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426326341.webp",
        "caption": "Tvoje nedělní ráno v pyžamu si zaslouží mnohem lepší kafe než instantní nouzovku.\n\nChceš zažít pohodu jako u nás u stolku, ale zrovna se ti nechce vylézat z postele? Chápeme. Zkouškové nebo náročný pracovní týden si občas žádají ranní klid bez mluvení s lidmi. Proto pro tebe máme naše čerstvě upražená výběrová zrnka na doma. Žádná věda ani kávový snobismus. Naši baristé ti balíček na baru rádi namelou přesně pro tvou oblíbenou přípravu – ať už máš doma french press, nebo si prostě zaléváš klasiku. Stačí zalít vodou a tvůj pokoj zaplaví vůně, která tě příjemně probudí do nového dne. Zvládneš to hravě i napůl spící.\n\nKup si balíček čerstvých zrn přímo na baru nebo na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kavomilci #coffeelover #specialtycoffeecech #prazskakavarna",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kavomilci #coffeelover #specialtycoffeecech #prazskakavarna"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426449765.webp",
        "caption": "Tohle útulné místo u okna je tajnou zbraní proti zkouškovému stresu.\n\n„Tady se píšou ty nejlepší seminárky a pije to nejlepší cappuccino,“ napsala o nás na Instagramu zákaznice Klára. A my jen tiše přikyvujeme. Když venku v Brně vrcholí zkouškové a v centru není k hnutí, náš stůl u okna je perfektní oáza. Rychlá wifi, božský klid na plánování nového týdne a k tomu ledový filtr, který tě nakopne bez následného útlumu. Potřebuješ pořádnou vzpruhu pro mozek? Vůně našich čerstvých skořicových šneků prokazatelně zlepšuje soustředění. Zapomeň na přeplněné knihovny. Přijď si ulovit svůj tichý koutek, vyladit projekty a užít si poctivé kafe od baristů, kteří tě znají jménem.\n\nNaplánuj si své příští produktivní odpoledne přes link v našem bio na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kamvbrne #specialtycoffeecech #kavarnavpraze #kamnakavu",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #brnocoffee #kamvbrne #specialtycoffeecech #kavarnavpraze #kamnakavu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426739612.webp",
        "caption": "Tohle flat white zachraňuje životy před těžkým pondělím a my máme důkaz.\n\nTahle slova od naší stálice nás neskutečně hřejí u srdce. V Zrnu totiž věříme, že kafe není jen kofeinový doping, ale rituál, který ti vrátí balanc. Zvlášť v neděli odpoledne, kdy už v hlavě straší blížící se týden nebo zkouškové. Na mlýnku máme zrovna čerstvý jednodruhový mikrolot z Kolumbie s přirozenými tóny peckového ovoce a mléčné čokolády. Žádná přepražená hořkost z řetězců. K tomu si dej našeho legendárního teplého šneka z poctivého másla bez chemie a pondělí tě prostě nerozhází. Napiš nám taky svou recenzi, neskutečně rádi je čteme!\n\nCelé naše kávové menu a aktuální nabídku zrnek najdeš na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #brnocoffee #coffeeplace #skoricovysnek #kavarnavpraze",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #brnocoffee #coffeeplace #skoricovysnek #kavarnavpraze"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426847425.webp",
        "caption": "Taky si každé ráno lžeš, že ti dneska bude stačit jen jedno kafe?\n\nSlíbil jsi sám sobě, že dneska dáš jen jeden šálek a dost? Chápeme. Zkouškové v plném proudu, venku začíná letní žár a ty před sebou máš nekonečný den. My tě neprozradíme. Když to jedno kafe bude náš poctivý double shot Flat white z čerstvě upražené jednodruhové arabiky a k odchodu si nenápadně odneseš ještě jedno ledové do kelímku, zůstane to čistě mezi námi. Na mlýnku máme zrovna božskou Etiopii s tóny borůvek, která tě spolehlivě probere i bez chemických sirupů. Stav se pro svou „jedinou“ dávku kofeinu.\n\nDej nám vědět do komentářů, kolikáté „poslední“ kafe dneska vlastně piješ! A naši aktuální nabídku zrn na doma najdeš na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #etiopie #specialtycoffeecech #kavarnavpraze #skoricovysnek",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #vyberovakava #flatwhite #etiopie #specialtycoffeecech #kavarnavpraze #skoricovysnek"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-kavarna-zrno/ig-posts/1781426947484.webp",
        "caption": "Nesnášíš ranní fronty na kafe? Máme pro tebe bleskové řešení.\n\nRanní shon tě nemusí připravit o chuťový zážitek. U nás v Zrnu chápeme, že každá minuta se počítá. Proto ti okamžitě po pípnutí kartou přistane v ruce naše ledové Cold brew. Macerujeme ho poctivých 16 hodin z čerstvých afrických zrn, takže chutná přirozeně sladce i bez cukru. K tomu popadni našeho legendárního skořicového šneka a můžeš běžet. Žádné zdržování, žádné kompromisy v kvalitě. Jen čistá energie s sebou na tvůj ranní sprint do kanclu.\n\nUšetři ráno čas a omrkni naše menu na https://kavarna-zrno.cz\n\n#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #brnocoffee #coldbrew #vyberovakava #specialtycoffeecech #kamnakavu #kava",
        "hashtags": "#kavarnazrno #zrno #kavarnazrnopraha #zrnovsrdci #brnocoffee #coldbrew #vyberovakava #specialtycoffeecech #kamnakavu #kava"
      }
    ]
  },
  {
    "slug": "studio-lumen",
    "company": "Studio Lumen",
    "industry": "Krása / Salon",
    "emoji": "✂️",
    "website": "https://studio-lumen.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427611118.webp",
        "caption": "Váš strach ze zničených vlasů je oprávněný, pokud kadeřník vynechal mikroskopickou diagnostiku.\n\nVáš tón pleti a struktura vlasu jsou zcela jedinečné. Proto barvení naslepo často končí zklamáním. V našem salonu začínáme každý rituál hloubkovou trichologickou analýzou pod mikroskopem. Zjistíme skutečný stav keratinových vazeb i to, jak vaše vlasy zvládnou letní UV záření a chlor. Na základě dat namícháme šetrnou barvu s plex-ochranou přesně pro váš typ pleti a tvar obličeje. Žádné tipování, jen čistá věda pro zdraví a maximální lesk. Domů od nás navíc dostanete přesný a jednoduchý plán péče, aby váš nový odstín zůstal sytý po celé týdny.\n\nDopřejte svým vlasům vědecky podloženou péči. Navštivte náš web https://studio-lumen.cz a objednejte se na svou osobní trichologickou diagnostiku ještě dnes.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #trichologie #zdravevlasy #vlasovapece #luxusnikadernictvi #mikroskopickaanalyza #barvenivlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #trichologie #zdravevlasy #vlasovapece #luxusnikadernictvi #mikroskopickaanalyza #barvenivlasu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427723691.webp",
        "caption": "Když si myješ vlasy každý den, abys nebyla mastná, ale pokožka spustí nouzový režim.\n\nČím víc myješ, tím víc mastíš. Klasický začarovaný kruh. První horké červnové dny a vlhkost tě nutí mýt si hlavu denně. Jenže pokožka hlavy v panice produkuje ještě víc mazu, aby se chránila. Výsledkem jsou dehydratované délky bez lesku a mastné kořínky už v poledne. Přestaň své vlasy trápit domácím experimentováním. Správná péče začíná pochopením biologie. V našem salonu sázíme na vědu. Pomocí mikroskopické analýzy odhalíme reálný stav tvé pokožky a navrhneme šetrný rituál, který tvé vlasy vrátí do rovnováhy bez agresivní chemie.\n\nChcete vědět, jak je na tom vaše pokožka? Objednejte se na mikroskopickou analýzu na https://studio-lumen.cz a sledujte náš profil pro další vědecky podložené tipy.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #vlasovaanalyza #trichologie #mikroskopickaanalyza #plexochrana #vlasy",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #vlasovaanalyza #trichologie #mikroskopickaanalyza #plexochrana #vlasy"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427843742.webp",
        "caption": "3 mýty o pánském stylingu, kterým věříte a zbytečně si tím kazíte první dojem.\n\nPlánujete úspěšný pracovní týden? Váš vzhled rozhoduje o prvním dojmu během vteřiny. Zapomeňte na levný gel z drogerie, který vlasy jen slepí. Moderní styling vyžaduje precizní střih na míru a produkty, které respektují biologii vaší pokožky. V našem salonu neslibujeme zázraky na počkání, ale doručíme dokonalost podloženou vědeckou analýzou. Během vaší proměny si navíc odpočinete u šálku výběrové kávy nebo sklenky prémiového prosecca. Spojujeme špičkovou péči s dokonalým rituálem relaxace, který vás restartuje před každou důležitou schůzkou. Tento týden máme v rezervačním systému poslední volná místa pro muže, kteří chtějí vypadat bezchybně.\n\nZajistěte si svůj bezchybný střih na tento týden. Rezervujte si svůj termín přes odkaz v našem bio.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystyling #panskystrih #vlasovaanalýza #mikroskopickaanalyza #promenavlasu #barvenivlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystyling #panskystrih #vlasovaanalýza #mikroskopickaanalyza #promenavlasu #barvenivlasu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781427959287.webp",
        "caption": "Špatný střih a nekvalitní styling zničí váš první dojem dřív než stihnete promluvit.\n\nDůležitá schůzka vyžaduje stoprocentní vzhled. Jenže běžný styling po dvou hodinách zplihne a levné produkty dráždí pokožku. Vydrží váš účes celodenní tlak? Představujeme exkluzivní drop: prémiový Matte Texture Clay a precizní střih na míru. Naše péče začíná vědeckou mikroskopickou analýzou vlasové pokožky. Navrhneme střih, který drží tvar sám a chráníme ho před ostrým červnovým sluncem. Uvolnili jsme poslední 3 last-minute termíny na tento víkend před Dnem otců. Získejte precizní střih a luxusní stylingový produkt jako dárek k ošetření.\n\nZarezervujte si svůj termín na tento víkend na https://studio-lumen.cz\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #prvnidojem #vlasovaveda #denotcu #mikroskopickaanalyza #ucesy #setrnezesvetleni",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #prvnidojem #vlasovaveda #denotcu #mikroskopickaanalyza #ucesy #setrnezesvetleni"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781428075437.webp",
        "caption": "Kulatý obličej není genetická vada, jen špatně zvolená geometrie střihu.\n\nZákulisí naší práce není o náhodném stříhání. Když do Studia Lumen usednete, nejdřív studujeme geometrii vaší tváře. Kulatý obličej? Žádný problém. Naši stylisté nepoužívají triky, ale čistou fyziku. Správným úhlem střihu a precizní strukturou dokážeme opticky prodloužit profil a vytvořit ostře řezané rysy. Dnes v salonu ladíme detaily pánského stylingu, který přežije i celodenní maraton schůzek bez ztráty objemu. Žádný ulepený vzhled, jen přirozená fixace a zdravé vlasy podložené vědeckým přístupem. Zítra je navíc Den otců – ideální čas nadělit si precizní péči, kterou si zasloužíte.\n\nDarujte si zasloužený rituál péče. Rezervujte si svůj čas pro precizní střih a individuální přístup na https://studio-lumen.cz.\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #geometriestrihu #panskystyling #vlasovapece #balayagepraha #ucesy #zdravevlasypraha",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #geometriestrihu #panskystyling #vlasovapece #balayagepraha #ucesy #zdravevlasypraha"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781428167715.webp",
        "caption": "Průměrný střih vás v byznysu stojí body za první dojem.\n\n„Měl jsem důležitou prezentaci a vlasy si žily vlastním životem. V Lumen mi udělali střih, který drží i bez tuny laku,“ říká náš klient Martin. Pánský střih u nás není jen o zkrácení délek. Používáme vědeckou analýzu růstu vlasů a navrhujeme styling, který respektuje tvar vaší lebky. Výsledek? Účes, který ráno upravíte za 30 vteřin a vydrží perfektní až do pozdního večera. Žádné kompromisy, jen špičková kosmetika a precizní práce našich vizionářů. Tento týden máme v rezervačním kalendáři poslední volná místa pro muže, kteří chtějí vypadat bezchybně.\n\nZajistěte si svůj precizní střih ještě dnes na https://studio-lumen.cz\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystrih #mensgroomingprague #vlasovapece #strihani #balayagepraha #promenavlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #panskystrih #mensgroomingprague #vlasovapece #strihani #balayagepraha #promenavlasu"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-studio-lumen/ig-posts/1781428259080.webp",
        "caption": "Necháváte vlasy po umytí volně uschnout, abyste je šetřila? Děláte obrovskou chybu.\n\nMokrý vlas bobtná. Voda uvnitř oslabuje jeho vazby a dlouhé schnutí pokožku hlavy i délky doslova unavuje. Výsledek? Matná barva, roztřepené konečky a ztráta elasticity. Máme pro vás třídenní výzvu. Po dalším mytí použijte termoochranu a vlasy vysušte fénem po směru růstu. Sledujte ten okamžitý rozdíl v lesku. Ve Studiu Lumen propojujeme luxus s vědou. Každý krok – od šetrného barvení s plex-ochranou po precizní střihy – stavíme na výsledcích mikroskopické analýzy vaší vlasové struktury. Už žádné hádání naslepo, jen jistota a zdraví. Napište nám do komentářů: Fénujete, nebo necháváte schnout?\n\nChcete vědět, jak podpořit zdraví a lesk své barvy před létem? Rezervujte si konzultaci na https://studio-lumen.cz\n\n#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #peceovlasy #vlasovaporadna #vlasy #barvenivlasu #promenavlasu",
        "hashtags": "#studiolumen #studiolumenpraha #lumenhair #lumensalon #zdravevlasy #peceovlasy #vlasovaporadna #vlasy #barvenivlasu #promenavlasu"
      }
    ]
  },
  {
    "slug": "vinarstvi-pod-strani",
    "company": "Vinařství Pod Strání",
    "industry": "Gastronomie / Vinařství",
    "emoji": "🍷",
    "website": "https://vinarstvi-podstrani.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428536359.webp",
        "caption": "Chladit víno v mrazáku pět minut před návštěvou je národní sport.\n\nVíkend končí, kufr auta je plný moravských pokladů a vy se nemůžete dočkat, až si doma nalijete. Jenže láhev má teplotu čerstvě uvařeného čaje. Žádnou paniku. Známe to všichni. Mokrá utěrka, mrazák a modlitba k vinařským bohům. U nás ve sklepě sice na správnou teplotu dbáme, ale doma? Tam platí jediné pravidlo: ať vám chutná. Žádné kroužení skleničkou podle pravítka a hledání tónů posekané trávy za úsvitu. Stačí dobrá společnost, otevřená láhev a klid v duši. Víno má lidi spojovat, ne stresovat složitou etiketou.\n\nA pokud vám zásoby na chlazení dochází, mrkněte na náš e-shop https://vinarstvi-podstrani.cz, kde si můžete doplnit moravské poklady přímo do chladničky. Jaký je pak váš zaručený trik na bleskové vychlazení? Napište nám do komentářů.\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #bezstresu #pohoda #sommelier #degustacevina #jiznimorava #frankovka",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #bezstresu #pohoda #sommelier #degustacevina #jiznimorava #frankovka"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428675763.webp",
        "caption": "Zapomeňte na neosobní degustační sály a masový turismus.\n\nU nás v Pod Strání věříme, že nejlepší víno chutná tam, kde se narodilo. V chladivém přítmí našeho historického sklepa, přímo u dubových sudů. Žádný spěch, žádný snobismus. Provedeme vás naší prací a představíme limitované šarže Ryzlinku vlašského, které v běžném obchodě nenajdete. Právě teď, když na Pálavě kvete réva, má sklep tu nejčistší atmosféru. Unikněte z horkého města na klidný víkend a zažijte poctivou degustaci s naším vinařem. Probereme život, půdu i tradici tří generací.\n\nRezervujte si svůj soukromý termín ve sklepě přes odkaz v našem biu.\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #palava #rodinnevinarstvi #frankovka #sommelier #ryzlinkrynsky #degustacevina",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #palava #rodinnevinarstvi #frankovka #sommelier #ryzlinkrynsky #degustacevina"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428787781.webp",
        "caption": "Jak letos poděkovat lidem, se kterými celý rok táhnete za jeden provaz?\n\nAť už chcete potěšit své věrné kolegy, nebo poslat poctivé poděkování za dobrou spolupráci partnerům, se kterými tvoříte společné dílo, zapomeňte na neosobní dárky z obchoďáků. Naše dárkové sety ukrývají to nejlepší z rodinného vinařství pod Strání – poctivé moravské řemeslo a tradici tří generací. Každou lahev pro vás s úctou zabalíme do elegantního boxu, kam rádi přidáme i váš osobní vzkaz. A o bezpečnou cestu až k jejich dveřím se spolehlivě postaráme, takže víno dorazí v naprostém pořádku do 48 hodin.\n\nVyberte si poctivé dárky, které zahřejí u srdce, na https://vinarstvi-podstrani.cz\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #darujmoravu #poctivevino #rodinnevinorstvi #sommelier #vinnysklep #vino",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #darujmoravu #poctivevino #rodinnevinorstvi #sommelier #vinnysklep #vino"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781428934210.webp",
        "caption": "Při přepravě archivních vín neriskuji, ale tito vinaři mě donutili změnit názor.\n\n„Objednal jsem limitovanou sadu na oslavu a bál se, v jakém stavu lahve dorazí. Přišly dokonale zabalené, s osobním vzkazem a v perfektní kondici. Chuť Ryzlinku z roku 2021 předčila všechna očekávání,“ píše náš zákazník Karel. Chápeme, že sběratelské kousky si zaslouží stoprocentní péči. Každou lahev balíme ručně s úctou k naší třígenerační práci ve vinohradu. Žádné poškození, žádné kompromisy. Jen čistá radost z poctivého moravského řemesla přímo u vás doma.\n\nDoplňte svůj domácí archiv poctivými kousky z našeho sklepa – odkaz najdete v bio.\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #archivnivino #poctivevino #jiznimorava #vino #rodinnevinarstvi #frankovka",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #archivnivino #poctivevino #jiznimorava #vino #rodinnevinarstvi #frankovka"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781429062744.webp",
        "caption": "Dokážete poznat víno z padesátileté vinice jen podle jednoho doušku?\n\nV roce 1974 vysadil náš děda na trati Pod Strání první keře Veltlínu. Dnes z nich sbíráme hrozny pro naše nejkomplexnější archivní kousky. Je to jedinečný zážitek jak pro zkušené vinaře, tak pro ty, kteří chtějí teprve ochutnat poctivý kus naší historie. Poznáte ve sklenici hluboké kořenité tóny staré révy, nebo vás zaskočí její zemitá síla? Právě pro Den otců jsme otevřeli rodinný archiv a připravili limitovanou sadu těchto vyzrálých klenotů s certifikátem původu. Lahve pro vás sami s úctou a péčí balíme do masivního dřeva přímo u nás ve sklepě, aby k vám domů doputovaly v naprostém pořádku. Dokážete odhadnout potenciál našeho Veltlínu? Napište nám do komentářů, jak starý archiv máte doma.\n\nUdělejte tátovi radost výjimečným dárkem a vyberte si limitovanou sadu na https://vinarstvi-podstrani.cz\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #rodinnevinoradost #jiznimorava #denotcu #frankovka #vinnysklep #vinarstvi",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #rodinnevinoradost #jiznimorava #denotcu #frankovka #vinnysklep #vinarstvi"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-vinarstvi-pod-strani/ig-posts/1781429162815.webp",
        "caption": "Jak poznáte poctivé víno bez složitých pouček a snobského kroužení sklenkou?\n\nZapomeňte na škrobené řeči o tónu kůže a dešťové vody. Skutečné řemeslo poznáte v ústech. Poctivé víno z rodinného vinařství má čistý charakter, který na nic nespěchá. Teď v červnu, kdy nám na vinicích pod Strání zrovna kvetou hlavy révy, dáváme víno do lahví s jediným cílem: ukázat vám opravdovou chuť jižní Moravy. Když k nám přijedete na degustaci do chladného historického sklepa, nebudeme vás zkoušet z chemie. Ukážeme vám, jak teplota okolí mění vůni vlašáku a proč příliš podchlazená lahev v horku úplně ztratí duši. Víno má spojovat, ne rozdělovat.\n\nChcete zažít poctivou degustaci bez snobismu? Vyberte si svůj letní termín na https://vinarstvi-podstrani.cz\n\n#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #jiznimorava #poctivevino #degustacevina #frankovka #milovnicivina #gastronomie",
        "hashtags": "#vinarstvipodstrani #vinarstvizmoravy #podstrani #moravskevino #jiznimorava #poctivevino #degustacevina #frankovka #milovnicivina #gastronomie"
      }
    ]
  },
  {
    "slug": "forma-fitness",
    "company": "Forma Fitness",
    "industry": "Fitness / Wellness",
    "emoji": "🏋️",
    "website": "https://forma-fitness.cz",
    "posts": [
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429389394.webp",
        "caption": "Ten moment, kdy tě naložená osa poprvé přitlačí k zemi a kolena se třesou.\n\nPocit, že na tebe v přeplněném fitku všichni zírají, když poprvé bojuješ s prázdnou osou, je hrozný. Pravda je ale taková, že každý nějak začínal. U nás ve Forma Fitness se nikdo nesměje. Naopak. Tady tě podržíme.\n\nNáš rychlý tip pro tvůj příští trénink: Než si naložíš váhu, piluj techniku u zdi nebo s kettlebellem před hrudníkem. Získáš jistotu v hlubokém sedu a ochráníš záda před zraněním. Příští týden v tom nemusíš plavat sám. Přijď si pro bezpečný start a fajn partu.\n\nPřestaň tápat v gymu sám. Klikni na https://forma-fitness.cz a začni trénovat chytře.\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #posilovani #silovytrenink #drepuj #cviceni #motivace #silasvaly",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #posilovani #silovytrenink #drepuj #cviceni #motivace #silasvaly"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429500873.webp",
        "caption": "Pravda o rychlé formě do plavek, kterou ti v klasických fitkách záměrně tají.\n\nCelerová šťáva ti týden před dovolenou břišáky nevykouzlí. Zapomeň na zázračné detoxy a pojď na činky. Ve Formě kašleme na pózy – když se ti u první osy klepou kolena, naši trenéři a komunita tě podrží. Shoď strach a začni s lidmi, co tě nenechají ve štychu.\n\nChceš se posunout dál? Klikni na odkaz v našem biu @forma.fitness\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #bezpoz #fitnesskomunita #realnyuspech #osobnitrener #posilovna #hubnuti",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #bezpoz #fitnesskomunita #realnyuspech #osobnitrener #posilovna #hubnuti"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429592798.webp",
        "caption": "Takhle vypadá gym, když zhasnou světla a všichni jdou konečně domů.\n\nV neděli večer plánuješ, jak od pondělka zničíš své limity. My mezitím neleníme. Když odejde poslední dříč, zhasneme hlavní světla, ale práce nekončí. Nastupuje noční směna. Čistíme osy, rovnáme kotouče na gram přesně a chystáme stroje tak, abys ráno mohl rovnou vlítnout na věc. Žádný chaos, žádné poházené jednoručky po zemi. Jen stoprocentně připravené bojiště pro tvůj další progres. Neděláme to pro efekt, ale protože víme, že detaily dělají výsledky. Tvá ranní dávka železa je připravena. Přijď si pro ni.\n\nZarezervuj si svůj ranní trénink přes odkaz v biu @forma.fitness na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenik #gymlife #bezpretvarky #funkcnitrenink #osobnitrener #motivace",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenik #gymlife #bezpretvarky #funkcnitrenink #osobnitrener #motivace"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429709290.webp",
        "caption": "Jak se naučit správný klik bez toho, aby se ti v gymu někdo smál?\n\nKliky nejsou o pouhém kývání hlavou k zemi. Skutečný klik vyžaduje pevné tělo a hrudník až dolů. Bezpečně a bez strachu, že se zraníš nebo tě bude někdo odsuzovat. Chápeme, že začít v obřím fitku plném pózérů může být děsivé. Proto jsme ve Forma Fitness vytvořili speciální startovací program pro začátečníky. Žádné složité stroje, žádný stres. Jen ty, profi trenér a parta lidí na stejné lodi. Naučíme tě základy, vybudujeme reálnou funkční sílu a zdravé tělo, které ti vydrží fungovat roky, ne jen jednu plavkovou sezónu. Nedělní večer je ideální čas udělat první krok.\n\nZajisti si své místo v našem programu pro začátečníky přes odkaz v biu na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnisila #bezstresu #klik #biomechanika #funkcnitrenink #cviceni",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnisila #bezstresu #klik #biomechanika #funkcnitrenink #cviceni"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429807590.webp",
        "caption": "Přestaň v pondělí čekat frontu na benchpress jako na banány.\n\nPondělí v běžném gymu je peklo. Všichni jedou prsa a ty jen smutně koukáš na obsazené lavičky. U nás ve Forma Fitness na fronty nehrajeme. Zatímco ostatní ztrácejí čas čekáním, naši trenéři už pro tebe chystají kruháč, který ti odpálí celé tělo. Žádné stroje, které tě jen omezují, ale poctivá práce s osou, kettlebelly a vlastní vahou. V zákulisí ladíme tréninky tak, abys ani vteřinu nestál. Naše komunita tě nenechá polevit a trenéři pohlídají každý tvůj pohyb. Zapomeň na pondělní benchpress chaos. Pojď makat chytře pod dohledem profíků. Volná místa na zítřek rychle mizí.\n\nRezervuj si svůj zítřejší funkční trénink přes odkaz v biu @forma.fitness.\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #bezfront #ostravafit #cviceni #posilovna #hubnuti",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #bezfront #ostravafit #cviceni #posilovna #hubnuti"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781429925132.webp",
        "caption": "Čekala jsem posměch a pohledy, ale místo toho mě hned podpořili.\n\nTohle nám napsala Nikola, která k nám poprvé přišla s obavou, že se ztrapní. Klasický příběh. Chceš začít cvičit, ale bojíš se, že vlezeš mezi namachrované lidi, co tě budou odsuzovat. U nás ve Forma Fitness to tak nefunguje. Žádné kradmé pohledy ani zrcadlové pózy. Naši certifikovaní trenéři tě naučí správnou techniku od úplného základu, bezpečně a bez stresu. Jsme komunita normálních lidí, kteří se navzájem táhnou nahoru. Nedělní večer je ideální čas přestat odkládat změnu. Sbal si věci a pojď na trénink, kde tě nenecháme se flákat, ale od první minuty tě podržíme.\n\nDomluv si svůj první zkušební trénink přes odkaz v biu @forma.fitness nebo přímo na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #sparingpartner #bezpoz #skutecnasila #zdravyzivotnistyl #biomechanika #silasvaly",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #sparingpartner #bezpoz #skutecnasila #zdravyzivotnistyl #biomechanika #silasvaly"
      },
      {
        "imageUrl": "https://nyvbxpjkwhcuugwevobu.supabase.co/storage/v1/object/public/ig-posts-forma-fitness/ig-posts/1781430022585.webp",
        "caption": "Stačí dvě procenta dole a tvůj výkon v gymu klesne o pětinu.\n\nNejsi slabý, jen jsi dehydratovaný. Mírný nedostatek vody ti sebere až pětinu síly. Pak máš pocit, že na tréninku nestíháš, a zbytečně pochybuješ o svém těle. Pojďme to změnit. Dáme si třídenní hydratační výzvu: každou hodinu vypij jednu sklenici čisté vody. Žádná věda, žádné složité stroje ani drahé doplňky. Jen jednoduchý návyk, který tě nakopne. U nás ve Forma Fitness tě nikdo soudit nebude, ať už začínáš s prázdnou osou nebo teprve sbíráš odvahu vejít. Jsme komunita, která tě podrží a nenechá tě se flákat.\n\nZačni měnit své návyky v přátelském prostředí. Rezervuj si zkušební lekci na https://forma-fitness.cz\n\n#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #ostravafit #zdravypohyb #cviceni #vyzivoveporadenstvi #hubnuti",
        "hashtags": "#formafitness #formafitnesscz #trenujveforme #tymforma #funkcnitrenink #ostravafit #zdravypohyb #cviceni #vyzivoveporadenstvi #hubnuti"
      }
    ]
  }
]
