/**
 * Export reference posts → lib/reference-data.ts
 *
 *   npx tsx scripts/export-references.ts [--per-brand=7]
 *
 * Reads every client flagged `config.isReference === true`, pulls its generated
 * posts (those with an image), and writes a static module the marketing site
 * imports. Re-run any time after generating/regenerating posts.
 */

import { writeFileSync } from "fs"
import { join } from "path"
import supabaseAdmin from "../supabase/admin"

interface ReferencePost {
    imageUrl: string
    caption: string
    hashtags: string
}
interface ReferenceBrand {
    slug: string
    company: string
    industry: string
    emoji: string
    website: string
    posts: ReferencePost[]
}

function emojiFor(industry: string, name: string): string {
    const s = `${industry} ${name}`.toLowerCase()
    if (s.includes("vina") || s.includes("víno") || s.includes("vino")) return "🍷"
    if (s.includes("kavár") || s.includes("kavar") || s.includes("café") || s.includes("coffee")) return "☕"
    if (s.includes("salon") || s.includes("kadeř") || s.includes("krása") || s.includes("beauty")) return "✂️"
    if (s.includes("fitness") || s.includes("wellness") || s.includes("gym")) return "🏋️"
    if (s.includes("restaur") || s.includes("gastro")) return "🍽️"
    if (s.includes("hotel") || s.includes("penzion") || s.includes("ubytov")) return "🏨"
    if (s.includes("e-com") || s.includes("eshop") || s.includes("e-shop")) return "🛒"
    if (s.includes("foto")) return "📸"
    return "✨"
}

async function main() {
    const perBrandArg = process.argv.slice(2).find(a => a.startsWith("--per-brand="))
    const perBrand = perBrandArg ? parseInt(perBrandArg.split("=")[1], 10) : 7

    console.log("📦 Exporting reference posts…")

    const { data: clients, error } = await supabaseAdmin
        .from("clients")
        .select("id, slug, name, website, config")
        .eq("is_active", true)

    if (error || !clients) {
        console.error("❌ Failed to load clients:", error?.message)
        process.exit(1)
    }

    const refClients = clients.filter(c => (c.config as any)?.isReference === true)
    if (refClients.length === 0) {
        console.warn("⚠️ No clients flagged isReference. Run scripts/seed-reference-clients.ts first.")
    }

    const brands: ReferenceBrand[] = []
    for (const c of refClients) {
        const cfg = (c.config as any) || {}
        const { data: posts } = await supabaseAdmin
            .from("ig_posts")
            .select("caption, hashtags, image_url, created_at")
            .eq("client_id", c.id)
            .not("image_url", "is", null)
            .order("created_at", { ascending: true })
            .limit(perBrand)

        const mapped: ReferencePost[] = (posts || []).map(p => ({
            imageUrl: p.image_url as string,
            caption: (p.caption as string) || "",
            hashtags: Array.isArray(p.hashtags) ? (p.hashtags as string[]).join(" ") : (p.hashtags || ""),
        }))

        const industry: string = cfg.industry || ""
        brands.push({
            slug: c.slug,
            company: c.name,
            industry,
            emoji: emojiFor(industry, c.name),
            website: c.website || cfg.website || "",
            posts: mapped,
        })
        console.log(`   ${emojiFor(industry, c.name)} ${c.name}: ${mapped.length} posts`)
    }

    const header = `// AUTO-GENERATED by scripts/export-references.ts — do not edit by hand.
// Real posts generated by the Chrlit engine for fictional demo brands (isReference).
// Re-run the export after (re)generating posts.

export interface ReferencePost {
    imageUrl: string
    caption: string
    hashtags: string
}
export interface ReferenceBrand {
    slug: string
    company: string
    industry: string
    emoji: string
    website: string
    posts: ReferencePost[]
}

export const REFERENCE_BRANDS: ReferenceBrand[] = `

    const out = header + JSON.stringify(brands, null, 2) + "\n"
    const target = join(process.cwd(), "lib", "reference-data.ts")
    writeFileSync(target, out, "utf-8")

    const totalPosts = brands.reduce((n, b) => n + b.posts.length, 0)
    console.log(`\n✅ Wrote ${brands.length} brands / ${totalPosts} posts → lib/reference-data.ts`)
}

main().catch(err => {
    console.error("💥 Export failed:", err)
    process.exit(1)
})
